# Generated by Django 4.1.7 on 2023-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_alter_event_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.CharField(max_length=120),
        ),
    ]
