# Generated by Django 4.1.7 on 2023-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default_pics/default_event.jpg', null=True, upload_to='event_pics'),
        ),
    ]
