# Generated by Django 4.1.7 on 2023-04-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0009_alter_event_image_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='speaker',
            new_name='speakers',
        ),
    ]
