# Generated by Django 4.1.7 on 2023-03-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='interest',
            field=models.TextField(default='Computer Security'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
