# Generated by Django 4.1.7 on 2023-04-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_pics/default_post.jpg', upload_to='post_pics'),
        ),
    ]
