# Generated by Django 4.1.7 on 2023-04-11 01:45

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_rename_speaker_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('29'), default_currency='USD', max_digits=11),
        ),
    ]
