# Generated by Django 4.1.7 on 2023-04-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0012_alter_event_fee_alter_event_fee_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='teacher',
        ),
    ]
