# Generated by Django 4.1.7 on 2023-03-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_major_teacher_student_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
