# Generated by Django 4.1.7 on 2023-03-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.ManyToManyField(to='users.major'),
        ),
    ]
