# Generated by Django 4.1.7 on 2023-03-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_teacher_major_teacher_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.major'),
        ),
    ]
