# Generated by Django 4.1.7 on 2023-03-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_major_teacher_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='supervisor status'),
        ),
    ]
