# Generated by Django 4.1.7 on 2023-03-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_teacher_interest_delete_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
