# Generated by Django 4.1.7 on 2023-04-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='default_pics/default_teacher.jpg', null=True, upload_to='teacher_pics'),
        ),
    ]
