# Generated by Django 4.1.7 on 2023-04-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_class_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='method',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sLorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae obcaecati unde nulla? Lorem, ipsum dolor. Lorem, ipsum.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirement',
            field=models.TextField(blank=True, default='Lorem ipsum dolor sit amet consectetur adipisicing elit.', null=True),
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
