# Generated by Django 4.1.7 on 2023-04-09 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_delete_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship', models.CharField(default='Quisque quis erat sed sem imperdiet blandit. ', max_length=100)),
                ('criterium', models.TextField(default='Phasellus a elit nisl.\n\nMorbi at massa non ipsum gravida faucibus.\n\nCurabitur at quam eget tortor tempor ultricies a vitae nibh.')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
    ]
