# Generated by Django 4.1.7 on 2023-03-28 01:17

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_duration',
            field=models.CharField(default='03 Hours', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default='06 Months', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('300.00'), default_currency='USD', max_digits=10),
        ),
    ]
