# Generated by Django 4.1.7 on 2023-04-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_scholarship_scholarship_alter_scholarship_criterium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='course',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='course',
            field=models.ManyToManyField(to='academics.course'),
        ),
    ]
