# Generated by Django 4.1.7 on 2023-04-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_scholarship_course_scholarship_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
