# Generated by Django 4.1.7 on 2023-04-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_scholarship',
        ),
    ]
