# Generated by Django 4.1.7 on 2023-04-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_course_fee_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='criterium',
            new_name='criterion',
        ),
    ]
