# Generated by Django 4.1.5 on 2023-02-09 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_pbulic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pbulic',
            new_name='public',
        ),
    ]
